# Change to your Company name (or keep as is)
# It will be displayed as the default author of the posts and the copyright owner in the Footer
  name: LYDDE Group
# Change to your contact email address
# It will be used for email link
  email: contact@lydde.com
# Change to your website
# It will be used in posts
  site: https://lydde.com