# ---
# Welcome to LYDDE Group Jekyll Theme!
# Version : 1.0.0
# ---
# This site is a bootstrap 5.3 theme for Jekyll engine
# This config file is meant for settings that affect your whole site, values
# which you are expected to set up once and rarely edit after that.
# Others settings are in /_settings/
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#

#
# Build settings
#
# theme: jekyll-theme-lydde

#
# Site
#
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
#
title: Symphony
description: "This is a bootstrap 5 theme for Jekyll engine"
email: your-email@example.com
author: LYDDE Group

#
# Brand
#
# These are used to marketize your brand. If you look in the HTML files,
# you will see them in the header and the NavMenu.
#
logo: "/assets/logo.png"
favicon: "assets/icons/favicon.ico"
tagline: A bootstrap 5 theme for Jekyll

#
# Localization
#
# These are used to assist search engine and browser exposing the right language to user.
#
timezone: Europe/Paris
language: en
locale: en_US

#
# Hosting
#
url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
permalink: /news/:categories/:title # the subpath of your posts, e.g. /news

#
# Collections
#
collections:
  categories:
    output: false
    
#
# Defaults values
#
defaults:
# all posts
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      image: /assets/images/post.jpeg
      author: author-1
# all categories
  - scope:
      path: ""
      type: categories
    values:
      layout: page
      image: /assets/images/page.jpeg
# all pages
  - scope:
      path: ""
      type: pages
    values:
      layout: page
      image: /assets/images/page.jpeg
#
# Theme Settings
#
settings:
# Google Analytics
  analytics: XXXXX
# Social Networks Information
  social:
    twitter:
      name: Twitter
      username: yakagamestudio
      link: https://twitter.com/yakagamestudio
      image: image-twitter.png
      card: summary
    facebook:
      name: Facebook
      username: yakagamestudio
      link: https://facebook.com/yakagamestudio
    instagram:
      name: Instagram
      username: yakagamestudio
      link: https://instagram.com/yakagamestudio
    linkedin:
      name: LinkedIn
      link: https://www.linkedin.com/showcase/yakagamestudio
    pinterest:
      username: YAKAGameStudio
      link: https://www.pinterest.fr/
    twitch:
      username: yakagamestudio
      link: https://www.twitch.tv/
    youtube:
      link: https://www.youtube.com/channel/UCqhzZEPsQ18xUt0vc1pekCw
  webmaster:
    verification:
      google: XXX
      bing: XXX
      alexa: XXX
      yandex: XXX
      baidu: XXX
      facebook: XXX
  theme:
    color:
      primary: #FFFFFF
#
# Plugin
#
plugins:
  - jekyll-relative-links
  - jekyll-github-metadata  #https://github.com/jekyll/github-metadata
  - jekyll-redirect-from

relative_links:
  collections: true

#
# Files excluded
#
exclude:
  - readme.md
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/