# ---
# Welcome to LYDDE Group Jekyll Theme!
# Version : 1.0.0
# ---
# This site is a bootstrap 5.3 theme for Jekyll engine
# This config file is meant for settings that affect your whole site, values
# which you are expected to set up once and rarely edit after that.
# Others settings are in /_settings/
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#

#
# Build settings
#
# theme: jekyll-theme-lydde

#
# Site
#
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
#
title: Symphony
description: "This is a bootstrap 5 theme for Jekyll engine"

#
# authors
#
author: LYDDE Group
authors:
  default:
    name: LYDDE Group
    email: contact@lydde.com
    site: https://lydde.com
  author-1:
    name: Author 1
    position: An editor at Blogzine
    email: contact@yaka.games
    picture: "/assets/images/avatar1.jpg"
    social:
      twitter:
        username: author-1
        link: https://twitter.com/
      github:
        name: GitHub
        username: author-1
        link: https://github.com/author-1
      linkedin:
        name: LinkedIn
        link: https://www.linkedin.com/author-1
      blog: 
        link: https://yaka.games
    description: >
      Suspendisse vel tellus efficitur, placerat quam ullamcorper, congue velit. 
      Nullam rhoncus luctus semper. Sed at vestibulum arcu, eu ornare erat. 
      Nunc nibh elit, egestas eget finibus eget, vestibulum et arcu. Quisque luctus in nisi in dapibus. 
      Aenean eu nisl ut sapien maximus interdum ut ut ipsum. Nam tortor leo, ultrices dignissim varius a, luctus quis purus. 
      Nam a sapien sed risus porta aliquet a vitae leo. Fusce bibendum, lectus a pellentesque sollicitudin, risus nisi dictum ante, a eleifend elit eros vitae mauris. Phasellus porttitor, augue eu accumsan vulputate, enim nulla dignissim mauris, eget eleifend sapien sapien vel lectus. Nam ultrices suscipit sapien, vitae facilisis dui volutpat ut. Maecenas id nulla mollis, consectetur nisl tristique, vulputate odio. Sed in auctor arcu. Nullam sit amet lacus quis urna sollicitudin pretium.

#
# Brand
#
# These are used to marketize your brand. If you look in the HTML files,
# you will see them in the header and the NavMenu.
#
logo: "/assets/logo.png"
favicon: "assets/icons/favicon.ico"
tagline: A bootstrap 5 theme for Jekyll

#
# Localization
#
# These are used to assist search engine and browser exposing the right language to user.
#
timezone: Europe/Paris
language: en
locale: en_US

#
# Hosting
#
url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "jekyll-lydde-theme" # the subpath of your site, e.g. /blog
permalink: /news/:categories/:title # the subpath of your posts, e.g. /news

#
# Collections
#
collections:
  categories:
    output: false
    
#
# Defaults values
#
defaults:
# all posts
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      image: /assets/images/post.jpeg
      author: author-1
# all categories
  - scope:
      path: ""
      type: categories
    values:
      layout: page
      image: /assets/images/page.jpeg
# all pages
  - scope:
      path: ""
      type: pages
    values:
      layout: page
      image: /assets/images/page.jpeg
#
# Theme Settings
#
settings:
# Google Analytics
  analytics: XXXXX
# Social Networks Information
  social:
    twitter:
      name: Twitter
      username: yakagamestudio
      link: https://twitter.com/yakagamestudio
      image: image-twitter.png
      card: summary
    facebook:
      name: Facebook
      username: yakagamestudio
      link: https://facebook.com/yakagamestudio
    instagram:
      name: Instagram
      username: yakagamestudio
      link: https://instagram.com/yakagamestudio
    linkedin:
      name: LinkedIn
      link: https://www.linkedin.com/showcase/yakagamestudio
    pinterest:
      username: YAKAGameStudio
      link: https://www.pinterest.fr/
    twitch:
      username: yakagamestudio
      link: https://www.twitch.tv/
    youtube:
      link: https://www.youtube.com/channel/UCqhzZEPsQ18xUt0vc1pekCw
  webmaster:
    verification:
      google: XXX
      bing: XXX
      alexa: XXX
      yandex: XXX
      baidu: XXX
      facebook: XXX
# Theme Color and Fonts
  theme:
    color:
      primary: #ffa500
      secondary: #ffbf00
# Menu links
  menus:
    header:
      - title: Home Menu
        position: left
        links:
        - title: Home
          link: "/"
        - title: News
          link: "/news/"
      - title: Network
        location: header
        links:
        - title: Studio
          link: https://yaka.studio
        - title: Play
          link: https://yaka.studio
          icon: 
    footer:
      - title: Footer Menu 1
        links:
        - title: Link 1
          link: "/news/"
        - title: Link 2
          link: "/news/"
        - title: Link 3
          link: https://yaka.studio
      - title: Footer Menu 2
        location: footer
        links:
        - title: Link 1
          link: "/news/"
        - title: Link 2
          link: "/news/"
        - title: Link 3
          link: https://yaka.studio
# Sharing
  share:
    twitter: https://twitter.com/share?url=
    facebook: https://www.facebook.com/sharer/sharer.php?u=
    linkedin: https://www.linkedin.com/shareArticle?url=
#
# Plugin
#
plugins:
  - jekyll-relative-links
  - jekyll-github-metadata  #https://github.com/jekyll/github-metadata
  - jekyll-redirect-from

relative_links:
  collections: true

#
# Files excluded
#
exclude:
  - readme.md
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/